import type { BoneDef, Rig, ViewConfig, ViewId } from './types.js';

/**
 * Bone lengths are fractions of stature (1.0 = sole to crown) and follow the
 * classic 7.5-heads canon used in anatomical drawing, with hip height at ~0.53
 * of stature. The rig is authored for the figure's LEFT side and the center
 * chain; the right side is generated by mirroring, so a symmetric pose needs
 * the same joint angles on both sides.
 *
 * `restAngle` is the bone's angle relative to its parent bone in the neutral
 * standing pose. A pose therefore expresses joint rotations the way anatomy
 * does: as a deviation from anatomical neutral.
 */
const CENTER_BONES: readonly BoneDef[] = [
  { id: 'pelvis', parent: null, attach: 'end', length: 0.1, restAngle: 0, side: 'center', group: 'torso' },
  { id: 'spine', parent: 'pelvis', attach: 'end', length: 0.17, restAngle: 0, side: 'center', group: 'torso' },
  { id: 'neck', parent: 'spine', attach: 'end', length: 0.06, restAngle: 0, side: 'center', group: 'torso' },
  { id: 'head', parent: 'neck', attach: 'end', length: 0.13, restAngle: 0, side: 'center', group: 'head' },
];

const LEFT_BONES: readonly BoneDef[] = [
  {
    id: 'clavicleL',
    parent: 'spine',
    attach: 'end',
    length: 0.1,
    restAngle: -90,
    side: 'left',
    group: 'torso',
    lateral: true,
  },
  { id: 'upperArmL', parent: 'clavicleL', attach: 'end', length: 0.165, restAngle: -90, side: 'left', group: 'arm' },
  { id: 'forearmL', parent: 'upperArmL', attach: 'end', length: 0.145, restAngle: 0, side: 'left', group: 'arm' },
  { id: 'handL', parent: 'forearmL', attach: 'end', length: 0.055, restAngle: 0, side: 'left', group: 'arm' },
  {
    id: 'hipL',
    parent: 'pelvis',
    attach: 'start',
    length: 0.085,
    restAngle: -90,
    side: 'left',
    group: 'torso',
    lateral: true,
  },
  { id: 'thighL', parent: 'hipL', attach: 'end', length: 0.245, restAngle: -90, side: 'left', group: 'leg' },
  { id: 'shinL', parent: 'thighL', attach: 'end', length: 0.245, restAngle: 0, side: 'left', group: 'leg' },
  {
    id: 'footL',
    parent: 'shinL',
    attach: 'end',
    length: 0.09,
    restAngle: 70,
    side: 'left',
    group: 'leg',
    foot: true,
    directional: true,
  },
];

const RIGHT_SUFFIX = /L$/;

const mirrorId = (id: string): string => (RIGHT_SUFFIX.test(id) ? id.replace(RIGHT_SUFFIX, 'R') : id);

const mirrorBone = (bone: BoneDef): BoneDef => ({
  ...bone,
  id: mirrorId(bone.id) as BoneDef['id'],
  parent: bone.parent === null ? null : (mirrorId(bone.parent) as BoneDef['id']),
  side: 'right',
});

export const DEFAULT_RIG: Rig = {
  name: 'humanoid-2d',
  // Parents precede children, so a single forward pass solves the chain.
  bones: [...CENTER_BONES, ...LEFT_BONES, ...LEFT_BONES.map(mirrorBone)],
};

/**
 * Views are 2D projections of a 3D body, so they only need two foreshortening
 * factors plus a rule for which way the feet point.
 */
export const VIEWS: Record<ViewId, ViewConfig> = {
  front: { lateralScale: 1, footScale: 0.45, mirrorDirectional: true },
  back: { lateralScale: 1, footScale: 0.45, mirrorDirectional: true },
  side: { lateralScale: 0.18, footScale: 1, mirrorDirectional: false },
  'three-quarter': { lateralScale: 0.7, footScale: 0.8, mirrorDirectional: false },
};
