import type { BoneDef, Rig } from './types.js';
import type { Vec3 } from './vec3.js';

/**
 * Bone lengths are fractions of stature (1.0 = sole to crown) and follow the
 * classic 7.5-heads canon used in anatomical drawing, with hip height at ~0.53
 * of stature. The rig is authored for the figure's LEFT side and the center
 * chain; the right side is generated by mirroring.
 *
 * The figure stands at the origin facing +z, with +x its anatomical left and
 * +y up. Every bone carries its rest direction and its two anatomical rotation
 * axes as explicit vectors - the whole sign convention of the pose format is
 * data in this file, not logic in the solver.
 */
const UP: Vec3 = [0, 1, 0];
const DOWN: Vec3 = [0, -1, 0];
const LEFT: Vec3 = [1, 0, 0];
const FORWARD: Vec3 = [0, 0, 1];

/** Feet rest pointing forward, dropped a little toward the floor. */
const FOOT_DROP_DEG = 20;
const FOOT_DIR: Vec3 = [0, -Math.sin((FOOT_DROP_DEG * Math.PI) / 180), Math.cos((FOOT_DROP_DEG * Math.PI) / 180)];

const CENTER_BONES: readonly BoneDef[] = [
  // Positive flex bends forward, positive abduct leans toward the figure's left.
  { id: 'pelvis', parent: null, attach: 'end', length: 0.1, dir: UP, flexAxis: LEFT, abductAxis: [0, 0, -1], twistAxis: UP, side: 'center', group: 'torso' },
  { id: 'spine', parent: 'pelvis', attach: 'end', length: 0.17, dir: UP, flexAxis: LEFT, abductAxis: [0, 0, -1], twistAxis: UP, side: 'center', group: 'torso' },
  { id: 'neck', parent: 'spine', attach: 'end', length: 0.06, dir: UP, flexAxis: LEFT, abductAxis: [0, 0, -1], twistAxis: UP, side: 'center', group: 'torso' },
  { id: 'head', parent: 'neck', attach: 'end', length: 0.13, dir: UP, flexAxis: LEFT, abductAxis: [0, 0, -1], twistAxis: UP, side: 'center', group: 'head' },
];

const LEFT_BONES: readonly BoneDef[] = [
  // Shoulder girdle: flex swings the shoulder forward, abduct shrugs it up.
  { id: 'clavicleL', parent: 'spine', attach: 'end', length: 0.1, dir: LEFT, flexAxis: [0, -1, 0], abductAxis: FORWARD, twistAxis: LEFT, side: 'left', group: 'torso' },
  // Arm: flex raises it forward, abduct lifts it sideways away from the body,
  // positive twist rotates it externally.
  { id: 'upperArmL', parent: 'clavicleL', attach: 'end', length: 0.165, dir: DOWN, flexAxis: [-1, 0, 0], abductAxis: FORWARD, twistAxis: UP, side: 'left', group: 'arm' },
  { id: 'forearmL', parent: 'upperArmL', attach: 'end', length: 0.145, dir: DOWN, flexAxis: [-1, 0, 0], abductAxis: FORWARD, twistAxis: UP, side: 'left', group: 'arm' },
  { id: 'handL', parent: 'forearmL', attach: 'end', length: 0.055, dir: DOWN, flexAxis: [-1, 0, 0], abductAxis: FORWARD, twistAxis: UP, side: 'left', group: 'arm' },
  // Pelvic girdle, mirroring the shoulder girdle one storey down.
  { id: 'hipL', parent: 'pelvis', attach: 'start', length: 0.085, dir: LEFT, flexAxis: [0, -1, 0], abductAxis: FORWARD, twistAxis: LEFT, side: 'left', group: 'torso' },
  // Leg: hip flex swings the thigh forward; the knee's flex axis points the
  // other way, because a knee bends backward - that is anatomy, stated as data.
  { id: 'thighL', parent: 'hipL', attach: 'end', length: 0.245, dir: DOWN, flexAxis: [-1, 0, 0], abductAxis: FORWARD, twistAxis: UP, side: 'left', group: 'leg' },
  { id: 'shinL', parent: 'thighL', attach: 'end', length: 0.245, dir: DOWN, flexAxis: [1, 0, 0], abductAxis: FORWARD, twistAxis: UP, side: 'left', group: 'leg' },
  // Foot: positive flex is dorsiflexion (toes up), positive abduct turns the toes out.
  { id: 'footL', parent: 'shinL', attach: 'end', length: 0.09, dir: FOOT_DIR, flexAxis: [-1, 0, 0], abductAxis: UP, twistAxis: FOOT_DIR, side: 'left', group: 'leg' },
];

const RIGHT_SUFFIX = /L$/;

const mirrorId = (id: string): string => (RIGHT_SUFFIX.test(id) ? id.replace(RIGHT_SUFFIX, 'R') : id);

/** Plain directions reflect across the sagittal plane: negate x. */
const mirrorDir = (v: Vec3): Vec3 => [-v[0], v[1], v[2]];

/**
 * Rotation axes are pseudovectors: reflecting a rotation flips its sense, so
 * the mirrored axis keeps x and negates y and z. This is exactly what makes
 * "abduct = away from the midline" hold on both sides with no code branch.
 */
const mirrorAxis = (v: Vec3): Vec3 => [v[0], -v[1], -v[2]];

const mirrorBone = (bone: BoneDef): BoneDef => ({
  ...bone,
  id: mirrorId(bone.id) as BoneDef['id'],
  parent: bone.parent === null ? null : (mirrorId(bone.parent) as BoneDef['id']),
  dir: mirrorDir(bone.dir),
  flexAxis: mirrorAxis(bone.flexAxis),
  abductAxis: mirrorAxis(bone.abductAxis),
  twistAxis: mirrorAxis(bone.twistAxis),
  side: 'right',
});

export const DEFAULT_RIG: Rig = {
  name: 'humanoid',
  // Parents precede children, so a single forward pass solves the chain.
  bones: [...CENTER_BONES, ...LEFT_BONES, ...LEFT_BONES.map(mirrorBone)],
};
